FROM oven/bun:1-alpine AS builder

WORKDIR /app

COPY package.json bun.lock tsconfig.json ./
COPY prisma ./prisma

RUN bun install --frozen-lockfile

COPY lib ./lib
COPY modules ./modules

FROM oven/bun:1-alpine AS runner

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app/package.json ./
COPY --from=builder /app/tsconfig.json ./
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/lib ./lib
COPY --from=builder /app/modules ./modules

CMD ["bun", "run", "worker:indexing"]