FROM oven/bun:1-alpine

WORKDIR /app

COPY package.json bun.lock tsconfig.json ./
COPY prisma ./prisma
RUN bun install --frozen-lockfile

COPY lib ./lib
COPY modules ./modules

CMD ["bun", "run", "worker:indexing"]
